export const CATEGORIES = [
    { key: "Health", label: "Health" },
    { key: "Heat", label: "Heat" },
    { key: "Food", label: "Food" },
    { key: "Housing", label: "Housing" },
    { key: "Transportation", label: "Transportation" },
    { key: "Employment", label: "Employment" },
    { key: "Veterans", label: "Veterans" }
];

export const RESOURCES = [
    {
        type: "Primary",
        category: "Health",
        name: "Mt. San Rafael Hospital (ER & Clinic)",
        address: "410 Benedicta Ave, Trinidad, CO 81082",
        phone: "719-846-9213",
        website: "https://www.msrhc.org/",
        hours: "ER 24/7; Rural Clinic M-F 8a-7p, Sat 9a-3p (Walk-in)",
        notes: "Hospital, ER, clinic, imaging (incl. 3D mammogram). Rural Health Clinic: 719-846-2206.",
        tags: ["women", "mammography"]
    },
    {
        type: "Primary",
        category: "Health",
        name: "Mt. Carmel Wellness & Community Center",
        address: "911 Robinson Ave, Trinidad, CO 81082",
        phone: "719-845-4838",
        website: "https://mtcarmelcenter.org/",
        hours: "Mon–Fri 8a–5p",
        notes: "Wellness, screenings, help for Veterans. Nurse Practitioner on site.",
        tags: ["veterans"]
    },
    {
        type: "Primary",
        category: "Health",
        name: "LA‑H Counties District Health Dept. (Public Health & WIC)",
        address: "412 Benedicta Ave, Trinidad, CO 81082",
        phone: "719-846-2213",
        website: "https://la-h-health.colorado.gov/",
        hours: "Mon–Fri 8a–5p",
        notes: "Shots, WIC (women/infants/children), public health clinic.",
        tags: ["women", "wic"]
    },
    {
        type: "Primary",
        category: "Health",
        name: "Health Solutions – Trinidad (Behavioral Health)",
        address: "417 S Indiana Ave, Trinidad, CO 81082",
        phone: "719-846-4416",
        website: "https://www.health.solutions/",
        hours: "Mon–Fri 8a–5p (Crisis line 24/7)",
        notes: "Mental health care, crisis help, substance use.",
        tags: []
    },
    {
        type: "Primary",
        category: "Health",
        name: "Crossroads Turning Points – Trinidad",
        address: "1004 Carbon Pl, Trinidad, CO 81082",
        phone: "719-846-4481",
        website: "https://www.crossroadstp.org/locations",
        hours: "See site; many late hours",
        notes: "Substance use treatment.",
        tags: []
    },
    {
        type: "Primary",
        category: "Health",
        name: "Salud Family Health – Dental Clinic (Trinidad)",
        address: "928 Smith Ave, Trinidad, CO 81082",
        phone: "719-422-8810",
        website: "https://www.saludclinic.org/trinidad",
        hours: "Mon–Fri 8a–5p (opens 9a 1st & 3rd Wed)",
        notes: "Community dental clinic; Medicaid accepted; low‑cost options.",
        tags: ["dental"]
    },
    {
        type: "Primary",
        category: "Health",
        name: "Trinidad Family Dental",
        address: "2124 Freedom Rd, Trinidad, CO 81082",
        phone: "719-422-5696",
        website: "https://trinidadfamily.dental/",
        hours: "Mon–Fri 8:30a–4:30p",
        notes: "Family dentistry; accepts Medicaid; comprehensive care.",
        tags: ["dental"]
    },
    {
        type: "Primary",
        category: "Health",
        name: "New Image Advanced Dental (Amy Wilson, DDS)",
        address: "417 University St, Suite 1, Trinidad, CO 81082",
        phone: "719-846-7387",
        website: "https://trinidadsmiles.com/",
        hours: "Call for hours",
        notes: "General dentistry, implants, periodontics, orthodontics.",
        tags: ["dental"]
    },
    {
        type: "Primary",
        category: "Health",
        name: "Fishers Peak Dentistry",
        address: "1723 E Main St, Trinidad, CO 81082",
        phone: "719-846-4028",
        website: "https://www.fisherspeakdentistry.com/",
        hours: "Call for hours",
        notes: "Family dentistry.",
        tags: ["dental"]
    },
    {
        type: "Primary",
        category: "Health",
        name: "Maternal Mental Health Hotline (24/7)",
        address: "",
        phone: "1-833-852-6262",
        website:
            "https://mchb.hrsa.gov/programs-impact/national-maternal-mental-health-hotline",
        hours: "24/7 call or text (English/Español)",
        notes: "Confidential support for pregnant/postpartum parents.",
        tags: ["women", "mental-health"]
    },
    {
        type: "Primary",
        category: "Health",
        name: "Keep Trinidad Safe (Resource Hub)",
        address: "403 E First St, Trinidad, CO 81082",
        phone: "719-846-3310",
        website: "https://www.keeptrinidadsafe.com/",
        hours: "Mon–Fri 8a–5p",
        notes: "Harm reduction, substance use support, and mental health referrals.",
        tags: ["mental-health"]
    },
    {
        type: "Primary",
        category: "Food",
        name: "Mt. Carmel – Food Distribution",
        address: "Mt. Carmel Center, Trinidad, CO 81082",
        phone: "719-845-4894",
        website: "https://mtcarmelcenter.org/",
        hours: "See program options",
        notes: "Community Food Box Program (call 719-845-4875 to qualify).",
        tags: ["veterans"]
    },
    {
        type: "Primary",
        category: "Food",
        name: "Fishers Peak Soup Kitchen",
        address: "300-398 Church St, Trinidad, CO 81082",
        phone: "719-680-0427",
        website: "",
        hours: "Meals Mon–Fri 11a–12:15p",
        notes: "Hot meals and food baskets.",
        tags: []
    },
    {
        type: "Primary",
        category: "Food",
        name: "South Central Council of Governments",
        address: "1222 San Pedro Ave, Trinidad, CO 81082",
        phone: "719-846-4515",
        website: "",
        hours: "Call for hours",
        notes: "Home-delivered meals for eligible seniors.",
        tags: []
    },
    {
        type: "Primary",
        category: "Heat",
        name: "LEAP – Energy Help (Winter)",
        address: "219 S Chestnut St, Trinidad, CO 81082",
        phone: "719-846-2276",
        website: "https://cdhs.colorado.gov/leap",
        hours: "Nov 1 – Apr 30 (call)",
        notes: "Help with heat bills (gas, electric, propane, wood).",
        tags: []
    },
    {
        type: "Primary",
        category: "Housing",
        name: "Las Animas County Human Services – Housing",
        address: "219 S Chestnut St, Trinidad, CO 81082",
        phone: "719-846-2276",
        website:
            "https://remerg.com/resources/las-animas-county-department-of-human-services/",
        hours: "Mon–Fri 8a–4:30p",
        notes: "Rent help, shelter links, stabilization.",
        tags: []
    },
    {
        type: "Primary",
        category: "Housing",
        name: "Trinidad Housing Authority",
        address: "128 E First St, Trinidad, CO 81082",
        phone: "719-846-7204",
        website: "https://tha-co.com/",
        hours: "Mon–Thu 8a–4p; Fri 8a–12p",
        notes: "Public Housing and Section 8 vouchers.",
        tags: []
    },
    {
        type: "Primary",
        category: "Housing",
        name: "Corazon Square Apartments",
        address: "201 Raton St, Trinidad, CO 81082",
        phone: "719-846-8333",
        website: "",
        hours: "Call for availability",
        notes: "Senior low-income housing (Trinidad Housing Authority).",
        tags: []
    },
    {
        type: "Primary",
        category: "Housing",
        name: "Vista Del Rae Apartments",
        address: "1402 Atchison Ave, Trinidad, CO 81082",
        phone: "719-846-3388",
        website: "",
        hours: "Call for availability",
        notes: "Low-income housing.",
        tags: []
    },
    {
        type: "Primary",
        category: "Housing",
        name: "Casa Alegre Apartments",
        address: "717 W Adams St, Trinidad, CO 81082",
        phone: "719-846-3388",
        website: "",
        hours: "Call for availability",
        notes: "Low-income housing.",
        tags: []
    },
    {
        type: "Primary",
        category: "Housing",
        name: "Western Apartments",
        address: "411 E North Ave, Trinidad, CO 81082",
        phone: "719-846-7539",
        website: "",
        hours: "Call for availability",
        notes: "Low-income housing.",
        tags: []
    },
    {
        type: "Primary",
        category: "Housing",
        name: "Keep Trinidad Safe (Housing Support)",
        address: "403 E First St, Trinidad, CO 81082",
        phone: "719-846-3310",
        website: "https://www.keeptrinidadsafe.com/",
        hours: "Mon–Fri 8a–5p",
        notes: "Referrals and case management for housing instability.",
        tags: []
    },
    {
        type: "Primary",
        category: "Faith",
        name: "Most Holy Trinity Catholic Church (Aid)",
        address: "135 Church St, Trinidad, CO 81082",
        phone: "719-846-3369",
        website: "https://trinidadcatholic.org/",
        hours: "Call for ministry assistance",
        notes: "Financial aid (rent/utilities), meal delivery, and St. Vincent de Paul Food Pantry.",
        tags: []
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Spanish Peaks Regional Health – Outreach & Women’s Clinic",
        address: "129 Kansas Ave, Walsenburg, CO 81089",
        phone: "719-738-5200",
        website: "https://www.sprhc.org/",
        hours: "Call for hours",
        notes: "Women’s clinic/services; hospital & imaging nearby.",
        tags: ["women"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Spanish Peaks Regional Health – Diagnostic Imaging (Mammography)",
        address: "23500 US Hwy 160, Walsenburg, CO 81089",
        phone: "719-738-5152",
        website: "https://www.sprhc.org/diagnostic-imaging",
        hours: "Mammography Mon (see site)",
        notes: "Mammograms and women’s imaging.",
        tags: ["women", "mammography"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Pueblo Dept. of Public Health & Environment – Family Planning Clinic",
        address: "101 W 9th St, Pueblo, CO 81003",
        phone: "719-583-4380",
        website:
            "https://county.pueblo.org/public-health-department/family-planning-birth-control",
        hours: "Mon–Fri 8a–4:30p; some evenings",
        notes: "Low‑cost birth control, STI testing; confidential; se habla español.",
        tags: ["women", "family-planning"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "UCHealth – Associates in Women’s Health (OB‑GYN)",
        address: "1600 N Grand Ave, Suite 400, Pueblo, CO 81003",
        phone: "719-585-2500",
        website:
            "https://www.uchealth.org/locations/womens-health-center-pueblo/",
        hours: "Mon–Fri 8a–5p",
        notes: "OB‑GYN group providing prenatal & gynecology care.",
        tags: ["women", "obgyn"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "CARE Colorado – Abortion Clinic (Pueblo)",
        address: "1930 E Orman Ave, Pueblo, CO 81004",
        phone: "719-884-4070",
        website: "https://carecliniccolorado.com/",
        hours: "Appts Wed–Sat; phone 24/7",
        notes: "Medication & procedural abortion; info & support.",
        tags: ["women", "abortion"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Pueblo Community Health Center – Women’s Wellness Connection",
        address: "110 E Routt Ave, Pueblo, CO 81004",
        phone: "719-543-8711",
        website: "https://www.pueblochc.org/service/womens-wellness-connection/",
        hours: "Call for hours",
        notes: "Free breast & cervical screening for eligible patients (state WWC).",
        tags: ["women", "screening"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Planned Parenthood – Colorado Springs Westside Health Center",
        address: "3480 Centennial Blvd, Colorado Springs, CO 80907",
        phone: "719-475-7162",
        website:
            "https://www.plannedparenthood.org/health-center/colorado/colorado-springs/80907/colorado-springs-westside-health-center-3967-90210",
        hours: "Mon/Fri 8a–6p; Tue 9a–6p; Sat 8a–3p",
        notes: "Birth control, STI care, abortion services; online booking.",
        tags: ["women", "abortion", "family-planning"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Community Dental Health – Pueblo (Grand Avenue Dental)",
        address: "2320 N Grand Ave, Pueblo, CO 81003",
        phone: "719-542-5300",
        website: "https://communitydentalhealth.org/",
        hours: "Mon–Thu 8a–4p",
        notes: "Nonprofit low‑cost dental; dentures, extractions; serves uninsured/Medicaid.",
        tags: ["dental"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Pueblo Community Health Center – Dental Services",
        address: "110 E Routt Ave, Pueblo, CO 81004 (multiple sites)",
        phone: "719-543-8711",
        website: "https://www.pueblochc.org/service/dental-services/",
        hours: "M/T/Th/F 8a–5p; Wed 9a–5p",
        notes: "FQHC dental clinics (O'Rourke & East Side); accepts most payors; sliding scale.",
        tags: ["dental"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Pueblo Community College – Dental Hygiene Clinic",
        address: "415 Harrison St (Health Sciences Bldg), Pueblo, CO 81004",
        phone: "719-549-3286",
        website: "https://pueblocc.edu/Dental-Clinics",
        hours: "Varies by semester",
        notes: "Low‑cost preventive cleanings and x‑rays by supervised students.",
        tags: ["dental"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Raton Family Dental",
        address: "1100 S 2nd St, Suite C, Raton, NM 87740",
        phone: "575-215-5750",
        website: "https://www.ratonfamilydental.com/",
        hours: "Mon–Fri 8a–4:30p",
        notes: "Full‑service family dentistry near CO/NM border.",
        tags: ["dental"]
    },
    {
        type: "Secondary",
        category: "Food",
        name: "The Salvation Army – Pueblo Corps",
        address: "401 S Prairie Ave, Pueblo, CO 81005",
        phone: "719-543-3656",
        website: "https://pueblo.salvationarmy.org/",
        hours: "Tue & Thu 10a–12p",
        notes: "Food boxes, Pueblo area.",
        tags: []
    },
    {
        type: "Secondary",
        category: "Food",
        name: "Center Toward Self‑Reliance (Pantry)",
        address: "901 W 8th St, Pueblo, CO",
        phone: "719-546-1271",
        website: "https://cfdpueblo.org/service/food-pantry/",
        hours: "Mon/Tue/Wed/Fri 1–3:30p",
        notes: "Groceries for low‑income households.",
        tags: []
    },
    {
        type: "Secondary",
        category: "Food",
        name: "Care and Share – Mobile Markets",
        address: "Southern Colorado (various)",
        phone: "719-296-6995",
        website: "https://careandshare.org/",
        hours: "See mobile schedule online",
        notes: "Mobile markets across rural areas. Pueblo office: 719-296-6995",
        tags: []
    },
    {
        type: "Secondary",
        category: "Housing",
        name: "Westside CARES (Rent/Utilities)",
        address: "2808 W Colorado Ave, Colorado Springs, CO 80904",
        phone: "719-389-0759",
        website: "https://www.westsidecares.org/get-help/rent-utilities/",
        hours: "Mon–Thu 9:30a–12:30p (after 8th)",
        notes: "Emergency rent and utility help.",
        tags: []
    },
    {
        type: "Secondary",
        category: "Housing",
        name: "Catholic Charities of Central Colorado",
        address: "Colorado Springs, CO (Main: 228 N Cascade)",
        phone: "719-636-2345",
        website: "https://www.ccharitiescc.org/get-help/rent-utility-services/",
        hours: "Call for availability",
        notes: "Rent & utility assistance. (Family Connections: 719-578-1222)",
        tags: []
    },
    {
        type: "Secondary",
        category: "Heat",
        name: "2‑1‑1 Colorado – Statewide Helpline",
        address: "Colorado (statewide)",
        phone: "866-760-6489",
        website: "https://www.211colorado.org/",
        hours: "24/7",
        notes: "Call to find local help near you.",
        tags: []
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Spanish Peaks Regional Health Center",
        address: "23500 US Hwy 160, Walsenburg, CO 81089",
        phone: "719-738-5100",
        website: "https://www.sprhc.org/clinics",
        hours: "Clinic M-F 8a-4p; Walk-In Mon/Wed 5p-7p, Sat (2nd/4th) 9a-3p; ER 24/7",
        notes: "Hospital & clinics (nearby).",
        tags: []
    },
    {
        type: "Secondary",
        category: "Health",
        name: "UCHealth Parkview Medical Center (ER)",
        address: "400 W 16th St, Pueblo, CO 81003",
        phone: "719-584-4000",
        website:
            "https://www.uchealth.org/locations/uchealth-emergency-care-parkview-medical-center/",
        hours: "ER 24/7",
        notes: "Hospital & emergency care.",
        tags: []
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Pueblo Public Health – Clinic (General)",
        address: "101 W 9th St, Pueblo, CO 81003",
        phone: "719-583-4380",
        website: "https://county.pueblo.org/public-health-department/clinic",
        hours: "Mon–Fri 8a–4:30p; limited evenings",
        notes: "General clinic at PDPHE; se habla español.",
        tags: []
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Miners Colfax Medical Center (Raton, NM)",
        address: "203 Hospital Dr, Raton, NM 87740",
        phone: "575-445-3661",
        website: "https://www.minershosp.com/",
        hours: "ER 24/7; clinics vary",
        notes: "Hospital & clinics just south of CO line.",
        tags: []
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Raton VA CBOC (Veterans Clinic)",
        address: "1493 Whittier St, Raton, NM 87740",
        phone: "575-445-2391",
        website:
            "https://www.va.gov/new-mexico-health-care/locations/raton-va-clinic",
        hours: "Call for hours",
        notes: "Primary care & women’s health for eligible Veterans.",
        tags: ["women", "veterans"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "TRUE Center for Gender Diversity (Youth)",
        address: "Colorado Springs, CO (Children’s Hospital)",
        phone: "720-777-8783",
        website: "https://www.childrenscolorado.org/",
        hours: "Call for hours",
        notes: "Gender‑affirming care for youth (regional).",
        tags: []
    },
    {
        type: "Primary",
        category: "Health",
        name: "Diane Buscarello, LPC",
        address: "Trinidad, CO",
        phone: "",
        website: "https://www.psychologytoday.com/us/therapists/diane-buscarello-trinidad-co/812563",
        hours: "Call for appointment",
        notes: "Counseling for family stress, trauma, PTSD. Contact via Psychology Today or SonderMind.",
        tags: ["mental-health"]
    },
    {
        type: "Primary",
        category: "Health",
        name: "Colorado Crisis Services (Statewide)",
        address: "",
        phone: "1-844-493-8255",
        website: "https://coloradocrisisservices.org/",
        hours: "24/7",
        notes: "Immediate crisis support. Text 'TALK' to 38255.",
        tags: ["mental-health"]
    },
    {
        type: "Primary",
        category: "Food",
        name: "Compassion Food Bank (COMPA)",
        address: "2000 N Linden Ave, Trinidad, CO 81082",
        phone: "719-423-9138",
        website: "",
        hours: "4th Sat 10a–1:30p",
        notes: "Food assistance at Las Animas Fairgrounds.",
        tags: []
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Spanish Peaks Mental Health Center",
        address: "926 Russell Ave, Walsenburg, CO 81089",
        phone: "719-738-2386",
        website: "https://www.spmhc.org/",
        hours: "Call for hours",
        notes: "Outpatient/inpatient services, therapy, dual diagnosis.",
        tags: ["mental-health"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Health Solutions – Walsenburg",
        address: "926 Russell Ave, Walsenburg, CO 81089",
        phone: "719-545-2746",
        website: "https://www.health.solutions/",
        hours: "Call for hours; 24/7 crisis",
        notes: "Mental health crisis intervention & substance abuse treatment.",
        tags: ["mental-health"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Pinwheel Healing Center",
        address: "186 Hospital Dr, Raton, NM 87740",
        phone: "505-636-6100",
        website: "https://pinwheelhealing.com/",
        hours: "Call for hours",
        notes: "Counseling, PTSD/anxiety treatment, addiction treatment.",
        tags: ["mental-health"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Tri County Community Services (Raton)",
        address: "220 4th Ave, Raton, NM 87740",
        phone: "575-445-2754",
        website: "https://www.tccservices.org/",
        hours: "Call for hours",
        notes: "Therapy, medication management, crisis intervention.",
        tags: ["mental-health"]
    },
    {
        type: "Secondary",
        category: "Health",
        name: "Health Solutions Crisis Center (Pueblo)",
        address: "1310 Chinook Ln, Pueblo, CO 81001",
        phone: "719-545-2746",
        website: "https://www.health.solutions/",
        hours: "24/7 Walk-in",
        notes: "Immediate mental health crisis help for all ages.",
        tags: ["mental-health"]
    },
    {
        type: "Secondary",
        category: "Food",
        name: "Walsenburg WIC Clinic",
        address: "119 E Fifth St, Walsenburg, CO 81089",
        phone: "719-738-2650",
        website: "https://www.coloradowic.gov/",
        hours: "Mon–Thu 9a–3p",
        notes: "Nutrition for women/infants/children.",
        tags: ["women", "wic"]
    },
    {
        type: "Secondary",
        category: "Food",
        name: "Dorcas Circle Food Pantry",
        address: "911 Main St, Walsenburg, CO 81089",
        phone: "719-738-2291",
        website: "http://www.dorcascircle.org/",
        hours: "Tue/Thu (Call)",
        notes: "Food assistance.",
        tags: []
    },
    {
        type: "Secondary",
        category: "Food",
        name: "Raton Hunger Pantry",
        address: "430 N 2nd St, Raton, NM 87740",
        phone: "505-652-6769",
        website: "",
        hours: "2nd/4th Sat 11a–1p",
        notes: "Food distribution.",
        tags: []
    },
    {
        type: "Secondary",
        category: "Food",
        name: "Colfax County WIC (Raton)",
        address: "226 E 4th Ave, Raton, NM 87740",
        phone: "575-445-3601",
        website: "https://www.nmwic.org/",
        hours: "Mon–Fri 8a–5p",
        notes: "WIC services for families.",
        tags: ["women", "wic"]
    },
    {
        type: "Secondary",
        category: "Food",
        name: "Pueblo WIC Clinic",
        address: "Pueblo, CO (Multiple locations)",
        phone: "719-583-4392",
        website: "https://county.pueblo.org/wic",
        hours: "Call for hours",
        notes: "Nutrition support for women/children.",
        tags: ["women", "wic"]
    },
    {
        type: "Primary",
        category: "Health",
        name: "Mt. San Rafael Women's Clinic",
        address: "328 Bonaventure Ave, Trinidad, CO 81082",
        phone: "719-846-9213",
        website: "https://www.msrhc.org/",
        hours: "Call for appointment",
        notes: "OB-GYN and women's health services (Dr. Frederiksen, Mary Hund-Snyder).",
        tags: ["women"]
    },
    {
        type: "Primary",
        category: "Health",
        name: "Salud Family Health (Medical)",
        address: "911 Robinson Ave, Trinidad, CO 81082",
        phone: "719-422-8800",
        website: "https://www.saludclinic.org/trinidad",
        hours: "Mon–Fri 8a–5p",
        notes: "Medical, behavioral health, pharmacy. All ages/incomes accepted.",
        tags: []
    },
    {
        type: "Primary",
        category: "Housing",
        name: "Advocates Against Domestic Assault (AADA)",
        address: "Trinidad, CO",
        phone: "719-846-6665",
        website: "http://advocatesaba.org/",
        hours: "24/7 Safeline",
        notes: "Emergency shelter and transitional housing for domestic violence survivors.",
        tags: ["women", "safety"]
    },
    {
        type: "Primary",
        category: "Transportation",
        name: "South Central Council of Governments (Transit)",
        address: "1222 San Pedro Ave, Trinidad, CO 81082",
        phone: "719-845-1127",
        website: "http://sccog.net/",
        hours: "Mon–Fri (Call 24hr in advance)",
        notes: "Medical and errand rides for seniors and public in Huerfano/Las Animas.",
        tags: ["seniors"]
    },
    {
        type: "Primary",
        category: "Transportation",
        name: "Health First Colorado (NEMT)",
        address: "",
        phone: "1-855-267-2341",
        website: "https://hcpf.colorado.gov/non-emergent-medical-transportation",
        hours: "Call to schedule",
        notes: "Non-Emergent Medical Transportation for Medicaid members.",
        tags: []
    },
    {
        type: "Primary",
        category: "Employment",
        name: "Trinidad Workforce Center",
        address: "140 N Commercial St, Trinidad, CO 81082",
        phone: "719-846-7680",
        website: "https://cdle.colorado.gov/wfc",
        hours: "Mon–Fri 8a–4:30p",
        notes: "Job search, career counseling, training assistance, and unemployment info.",
        tags: ["veterans"]
    },
    {
        type: "Primary",
        category: "Employment",
        name: "Keep Trinidad Safe (Job Support)",
        address: "403 E First St, Trinidad, CO 81082",
        phone: "719-846-3310",
        website: "https://www.keeptrinidadsafe.com/",
        hours: "Mon–Fri 8a–5p",
        notes: "Job training, skills development, and employment connections.",
        tags: []
    },
    {
        type: "Primary",
        category: "Veterans",
        name: "Las Animas County Veterans Services",
        address: "200 E First St, Room 101, Trinidad, CO 81082",
        phone: "719-846-3940",
        website: "https://www.lasanimascounty.net/departments/veterans-services",
        hours: "Mon–Thu 7a–5:30p",
        notes: "Assistance with VA claims, pensions, death benefits, and medical enrollment.",
        tags: ["veterans"]
    },
    {
        type: "Primary",
        category: "Veterans",
        name: "American Legion Post 11",
        address: "204 S Chestnut St, Trinidad, CO 81082",
        phone: "719-967-1040",
        website: "https://www.facebook.com/AmericanLegionPost11TrinidadCO/",
        hours: "Club Mon 3p-10p; Call for other services",
        notes: "Community support, advocacy, and assistance for veterans and families.",
        tags: ["veterans"]
    },
    {
        type: "Primary",
        category: "Veterans",
        name: "Trinidad State College – Veteran Services",
        address: "600 Prospect St, Trinidad, CO 81082",
        phone: "719-846-5550",
        website: "https://trinidadstate.edu/veterans/",
        hours: "Mon–Fri 8a–5p",
        notes: "Education benefits, GI Bill assistance, and vocational rehabilitation.",
        tags: ["veterans"]
    },
    {
        type: "Primary",
        category: "Veterans",
        name: "Homes for All Veterans (HAV) – Rocky Mountain Human Services",
        address: "Regional (Call for support)",
        phone: "1-855-838-7428",
        website: "https://www.rmhumanservices.org/hav",
        hours: "Mon–Fri 8a–5p",
        notes: "Housing assistance and support services for veterans at risk of homelessness.",
        tags: ["veterans", "housing"]
    },
    {
        type: "Primary",
        category: "Veterans",
        name: "Keep Trinidad Safe (Veteran Support)",
        address: "403 E First St, Trinidad, CO 81082",
        phone: "719-846-3310",
        website: "https://www.keeptrinidadsafe.com/",
        hours: "Mon–Fri 8a–5p",
        notes: "Community resource connection and support services.",
        tags: ["veterans"]
    }
];
